version: '2'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - .ollama:/root/.ollama
    ports:
      - 11434:11434
  
  flask-app:
    image: llm_summary_app
    ports:
      - 5120:5120